name: Node.js Package

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@btime'
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GPR_SECRET }}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@btime'
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GPR_SECRET }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GPR_SECRET}}
